#!/usr/bin/env sh

# Hyprland-inspired BSP tiling.
yabai -m config layout                       bsp
yabai -m config window_placement             second_child
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config window_gap                   10
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config external_bar                 all:0:0
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="Finder" title="(Copy|Move|Info|Connect|Preferences)" manage=off
yabai -m rule --add subrole="AXDialog" manage=off
