#!/opt/homebrew/bin/lua

local config_dir = os.getenv("HOME") .. "/.config/sketchybar"
package.path = config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua;" .. package.path
package.cpath = package.cpath .. ";" .. os.getenv("HOME") .. "/.local/share/sketchybar_lua/?.so"

sbar = require("sketchybar")

sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()
sbar.event_loop()
